### ISSUE TITLE
Freeze Python Script with Popen, omxplayer and PIPE

### ISSUE THREAD

**Issue by gauthierlerouzic** [KenT2/pyomxplayer#1]
Hi guy,
Thanks for your project. I write a more simple python script to run a video in loop with omxplayer, and switch the video with using a sensor.
For this exemple, the sensor is a keyboard.
So the script mork weel, but after 3/4hours, the video freeze, and I can quit the script with my q key.
It's crazy. when I run the same command for omxplayer directly in the terminal, I have no troubles.
Si, I see you are using PIPE, subprocess, same things like me. I you already have this problem ?
This is the code :
`from subprocess import Popen, PIPE
import os, sys, signal
import getch

p = Popen(['omxplayer', '--loop','--genlog', '--no-osd','--pos','00:02:07','-o','both','-b','Documents/movie2.mp4'], stdin=PIPE, stdout=PIPE, stderr=PIPE, close_fds=True)
p

while True:
    char = getch.getch()
    if char =='a':
        p.stdin.write('i')
        p.stdin.flush()
    if char == 'q':
        os.system('pkill omxplayer')
        sys.exit(0)` 
All the best

**Comment by KenT2** [comment]
Sorry I can't help with this
I think there was an issue raised on the omxplayer github about use with stdin pipes a long while ago
Best to move to dbus as that is much better supported by the maintainers

**Comment by gauthierlerouzic** [comment]
Thank you very much!
I will see it in few hours.
I test the omxplayer alone, and it’s not the problem.
I think it’s really a PIpe problem...
All the best

Gauthier LE ROUZIC
gauthierlerouzic.com
+33 (0)6 51 59 13 61
